### ISSUE TITLE
[Wontfix] Cannot have more than 2 keys down at any time

### ISSUE THREAD

**Issue by goofanader** [goofanader/space-bar#1]
It might just be my computer, but it seems that using **love.keyboard.isDown()** only does up to two keys at a time. Using the pipeline I created for the KS Game might be the better way to go.

**Comment by goofanader** [comment]
WELP I FIGURED THE PROBLEM OUT

It's that my keyboard can't hold more than 2 keys at a time, but to fix this bug, we'd have to change the space bar to the shift or ctrl key... which would lose the game's double-meaning. What do

EDIT in that I mean the keyboard creators allowed for 2+ keys at a time when you hold the shift or ctrl key, but NOT for space bar.

**Comment by goofanader** [comment]
Well, I ain't fixing this any time soon, and I probably won't since the whole game is about using the space bar. Besides, it seems that most people don't just hold down space bar anyway? I'm not sure.

**Comment by eyfey** [comment]
I think it might just be your keyboard- I've been having no problems holding spacebar and moving up/down/side/diagonally/wherever

**Comment by goofanader** [comment]
Yeah, it's a hardware-based problem.... It's dependent on your keyboard, so like... it's a bug that can occur for some people but not all DX So dumb

Keyboard manufacturers assume that games will have the Shift or Ctrl keys held down while other buttons are pressed, but not space bar???? That's like, classic though!!!!

**Comment by eyfey** [comment]
yeah wow that is really dumb.
