### ISSUE TITLE
[Added] Game Over Message

### ISSUE THREAD

**Issue by eyfey** [goofanader/space-bar#10]
How hard would it be to make it so that a different message appears on the game over screen based on your score? 

Because HEAR ME OUT HERE-
what if we added something like 
score -> 0-50: no message
50-99: "You are humanity's last hope"
100-149: "If you cannot beat them, we will die"
149-199: "They were human once"
200-249: "It's all our fault"
250-299: "We shouldn't have played god"
300-349: "They are too strong"
350-399: "I'm sorry about your father"
400+: "We cannot win"

WE CAN'T HAVE THE PINK DOT BUT MAYBE WE CAN HAVE THIS??

**Comment by goofanader** [comment]
lol omg, YES this is a good idea, and it wouldn't be difficult at all

Where should the text be? Does it replace the "Game Over" text, unless you're at score 0-50?

And which score determines the message, hiscore or the player's score for the game?

**Comment by eyfey** [comment]
Definitely should be based on the player score- 
If there's room it can just be under the game over message, but if it makes things look too crowded or whatevs it can just replace it or maybe off to the side?? Or maybe if it's a different color it'd be fine? whatever looks best

**Comment by goofanader** [comment]
And it's added!

I decided to flip the Game Over message to be the new message, unless they get less than 50 points. Then it just says "Game Over". Also, made the messages be in all caps, adds urgency??? Maybe?

It's available for download on the [itch.io page](http://goofanader.itch.io/space-bar)

Let me know if I should change anything, yeah
