### ISSUE TITLE
Space Bar, as in an establishment that serves alcohol in space

### ISSUE THREAD

**Issue by goofanader** [goofanader/space-bar#11]
Hey @eyfey , would you be willing to make a screen that's a bar? I can use all the other sprites, but just like a new background would be great.

I was thinking this would be a super-secret-mode where the astronaut orders drinks from a space bar, with the bartender being the boss alien. The astronaut can't communicate with him, though, so to get your communicator, you have to find your spaceship. It's a game where you can always win, unlike the regular "Space Bar" mode where you will inevitably lose.

Something like that? I actually had a far more elaborate idea for it, but like... I wouldn't be able to get it done in time for when this game joins the Sharecart1000 package (which is Sunday)

**Comment by eyfey** [comment]
Can do! (bar as in drink/alcohol bar, right?)
Is it a scrolling background? or just one the size of the game window?

**Comment by eyfey** [comment]
Also can I also make a new big boss sprite for this that is exactly like the old one except with a bowtie????

**Comment by goofanader** [comment]
Not a scrolling background, the bar will change to space when the astronaut leaves the bar to look for his ship :) But the bar should be 1024 x 128 pixels, if possible. The opening screen should be the bar completely, no space (except like seen through a window or something). I can also scale an image up, but make sure that the ratio of the image is in 1024 x 128

YES BOWTIE IS NICE

**Comment by eyfey** [comment]
Okey dokes! I got work tonight and tomorrow morning, but I can get it done by tomorrow night~

**Comment by goofanader** [comment]
okay, cool! I'm gonna set you as the assignee yo

and if it doesn't get done by then, no worries. Just whenever you have time - I'm quite busy, I have so much to do for like the next 5 days DX

**Comment by eyfey** [comment]
Sorry, very shit went down on Friday so I got set back a lot- I'ma go get it done right now.

**Comment by eyfey** [comment]
![barimg](https://cloud.githubusercontent.com/assets/11142143/6433971/19fa4e42-c032-11e4-8b93-e78be0758f6c.png)
Look at this beautiful bar- (added to github)

**Comment by eyfey** [comment]
Let me know if you need anything fixed/changed/adjusted
